---
image: buluma/github-action-molecule:4.0.5

services:
  - docker:dind

variables:
  DOCKER_HOST: "tcp://docker:2376"
  PY_COLORS: 1

molecule:
  script:
    - image=${image} tag=${tag} molecule test
  rules:
    - if: $CI_COMMIT_REF_NAME == "master"
  retry: 1
  parallel:
    matrix:
      - image: "rockylinux"
        tag: "latest"
      - image: "fedora"
        tag: "latest"

galaxy:
  script:
    - ansible-galaxy role import --api-key ${GALAXY_API_KEY} ${CI_PROJECT_NAMESPACE} ${CI_PROJECT_NAME}
  rules:
    - if: $CI_COMMIT_TAG != null

# gitlab:
#   script:
#     - "curl -X POST --fail -F token=TOKEN -F ref=REF_NAME https://gitlab.com/api/v4/projects/33247529/trigger/pipeline"
