---
roles:
  - name: buluma.bootstrap
  - name: robertdebock.buildtools
  - name: buluma.cron
  - name: robertdebock.core_dependencies
  - name: robertdebock.epel
  - name: robertdebock.httpd
  - name: buluma.mysql
  - name: robertdebock.openssl
  - name: buluma.php
  - name: robertdebock.python_pip
  - name: robertdebock.selinux
collections:
  - name: ansible.posix
  - name: community.mysql
  - name: ansible.posix
  - name: community.crypto
