---
- name: Import assert.yml
  ansible.builtin.import_tasks: assert.yml
  delegate_to: localhost
  run_once: true
- name: Install requirements
  ansible.builtin.package:
    name: "{{ moodle_requirements }}"
    state: present
- name: Download and unpack moodle
  ansible.builtin.unarchive:
    creates: "{{ moodle_httpd_data_directory }}/moodle"
    dest: "{{ moodle_httpd_data_directory }}"
    group: "{{ moodle_httpd_group }}"
    mode: "0755"
    owner: "{{ moodle_httpd_owner }}"
    remote_src: true
    src: "{{ moodle_src }}"
  register: moodle_download_and_unpack
  retries: 3
  until:
    - moodle_download_and_unpack is succeeded
- name: Make directory
  ansible.builtin.file:
    group: "{{ moodle_httpd_group }}"
    mode: "{{ moodle_directory_mode }}"
    owner: "{{ moodle_httpd_owner }}"
    path: "{{ moodle_data_directory }}"
    state: directory
- name: Configure moodle
  ansible.builtin.template:
    dest: "{{ moodle_httpd_data_directory }}/moodle/config.php"
    group: "{{ moodle_httpd_group }}"
    mode: "0640"
    owner: "{{ moodle_httpd_owner }}"
    src: config.php.j2
- name: Setup cron job
  ansible.builtin.cron:
    job: /usr/bin/php {{ moodle_httpd_data_directory }}/moodle/admin/cli/cron.php >/dev/null
    name: moodle
    user: "{{ moodle_httpd_owner }}"
