---
- name: Prepare
  hosts: all
  become: true
  gather_facts: false
  roles:
    - role: buluma.bootstrap
    - role: buluma.buildtools
    - role: buluma.epel
    - role: buluma.mysql
      mysql_databases:
        - collation: utf8mb4_unicode_ci
          encoding: utf8mb4
          name: moodle
      mysql_users:
        - name: moodle
          password: moodle
          priv: moodle.*:ALL
    - role: buluma.openssl
      openssl_items:
        - common_name: "{{ ansible_facts['fqdn'] }}"
          name: apache-httpd
    - role: buluma.php
    - role: buluma.selinux
    - role: buluma.httpd
      httpd_vhosts:
        - name: moodle
          servername: moodle.example.com
    - role: buluma.cron
    - role: buluma.core_dependencies
  tasks:
    - name: Find EXTERNALLY-MANAGED files
      ansible.builtin.find:
        paths:
          - /usr/lib
          - /usr/local/lib
        patterns:
          - "EXTERNALLY-MANAGED"
        recurse: true
        file_type: file
      register: externally_managed_files
    - name: Rename EXTERNALLY-MANAGED files
      ansible.builtin.command:
        cmd: "mv {{ item.path }} {{ item.path }}.old"
      loop: "{{ externally_managed_files.files }}"
      loop_control:
        label: "{{ item.path }}"
      when: externally_managed_files.matched > 0
      args:
        creates: "{{ item.path }}.old"
      changed_when: true
    - name: Install python_pip role
      ansible.builtin.import_role:
        name: buluma.python_pip
