---
name: Release Drafter
"on":
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  pull_request_target:
  push:
    branches:
      - master
      - main
      - dependabot/**
      - renovate/**
      - testing
    paths-ignore:
      - "**/README.md"
      - "**/CHANGELOG.md"
permissions: write-all
concurrency:
  cancel-in-progress: true
  group: ${{ github.ref }}-${{ github.workflow }}
jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: release-drafter/release-drafter@main
        with:
          config-name: release-drafter.yml
          disable-autolabeler: false
